#pragma once

#include "Arduino.h"

#define SERIAL_LOGS 1

enum
{
  CONFIG_TEMPERATURE_HUMIDITY_INTERVAL_SEC = 64,
  CONFIG_TEMPERATURE_THRESHOLD_DEGREES,
  CONFIG_HUMIDITY_THRESHOLD_PERCENT,
  CONFIG_TEMPERATURE_CORRECTION_DEGREES,
  CONFIG_HUMIDITY_CORRECTION_PERCENT,
  CONFIG_CO2_START_CALIBRATION
};

#define CHANNEL_DEFAULT 1
#define CHANNEL_TEMPERATURE 2
#define CHANNEL_HUMIDITY 3
#define CHANNEL_CO2 4
#define CHANNEL_TVOC 5
